version: '3.8'

services:

  client:
    image: xanderdaigh/stm_test:client
    container_name: react_app_container
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
     - api
    deploy:
      resources:
        limits:
          memory: 0.4G
    links:
     - caddy:api
    networks:
      - local
    ports:
     - "3000:3000"
     - "3000:3000/udp"

  api:
    image: xanderdaigh/stm_test:server
    container_name: express_api_container
    restart: unless-stopped
    depends_on:
      - caddy
    deploy:
      resources:
        limits:
          memory: 0.4G
    networks:
      - local
    ports:
     - "5000:5000"
     - "5000:5000/udp"
    

  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    container_name: caddy_container
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      resources:
        limits:
          memory: 0.1G
    cap_add:
      - NET_ADMIN
    networks:
      - local
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "4000:4000"
      - "4000:4000/udp"

volumes:
  caddy_data:
  caddy_config:

networks:
  local: