version: '3.8'

services:

  client:
    image: xanderdaigh/stm_test:react_app
    container_name: react_app_container
    restart: unless-stopped
    ports:
     - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
     - api
    deploy:
      resources:
        limits:
          memory: 0.4G

  api:
    image: xanderdaigh/stm_test:express_api
    restart: unless-stopped
    container_name: express_api_container
    ports:
     - "4000:4000"
    deploy:
      resources:
        limits:
          memory: 0.4G

  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    container_name: caddy_container
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      resources:
        limits:
          memory: 0.1G

volumes:
  caddy_data:
  caddy_config: